# Generated by Django 3.2.6 on 2021-10-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_myform_on_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=300)),
                ('on_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Myform',
        ),
    ]
