# Generated by Django 3.2.6 on 2021-10-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211001_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='message',
            field=models.CharField(max_length=300),
        ),
    ]
