# Generated by Django 3.2.6 on 2021-10-02 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_on_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='on_date',
        ),
    ]
