# Generated by Django 3.2.6 on 2021-10-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='message',
            field=models.CharField(max_length=300),
        ),
    ]
